### ISSUE TITLE
directive auto-registration

### ISSUE THREAD

**Issue by crherman7** [crherman7/rechunk#79]
**Is your feature request related to a problem? Please describe.**
Currently you must register each component you want to be published in the rechunk.json configuration file. This is fine for right now it can get kind of verbose syncing those.

**Describe the solution you'd like**
Use a top level directive like `"use rechunk";` to tell the babel compiler to make this a component that should be read from the rechunk service. The babel plugin and cli would need to be updated.

**Describe alternatives you've considered**
Leave it the way it is.

**Comment by devs9** [comment]
@crherman7 great idea👍  it will make it easier to use the `rechunk`, so I'd like to see us implement it 😄
